[package]
name = "rhai_egui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.17.0"
rhai = "1"

[dev-dependencies]
eframe = "0.17.0"